### ISSUE TITLE
Unable to build the Rust SDK (macOs)

### ISSUE THREAD

**Issue by DoctorNigel** [hiero-ledger/hiero-sdk-rust#555]
### Description

I wanted to test the Rust SDK despite it being flagged as not ready for production. Unfortunately I'm getting this error: failed to run custom build command for `hedera-proto v0.7.0` when trying to build the project

The Rust version is 1.70.0, Swift 5.8.1 alongside latest version of task.

Any insights would be of massive help.

### Steps to reproduce

1. import hedera crate (0.18.0) in the Cargo.toml file
2. cargo build 

### Hedera network

testnet

### Version

v0.18.0

### Operating system

macOS

**Comment by izik1** [comment]
Hi! It seems that the README is out of date on requirements.

Current build requirements are latest rust stable (which you have), and `protoc` which, given where the error happened, I don't think you have.

`task` is an alternative way to run `cargo build` effectively (and it's so that similar commands can be available in all SDKs) and is _not_ a requirement to have the Hedera Rust SDK as a dependency.

Presumably you use homebrew given that you're on macOS, if that is the case https://formulae.brew.sh/formula/protobuf is likely what you're looking for.

I'll leave this open until:
1. You can confirm that installing protoc fixes the build error
2. I update the README to list _current_ build requirements

**Comment by DoctorNigel** [comment]
Hey again!

You were spot on. It works perfectly, tried and tested.

Thanks for replying so quickly. 

Godspeed
