### ISSUE TITLE
Possible bug in token_transfer_with_decimals

### ISSUE THREAD

**Issue by DoctorNigel** [hiero-ledger/hiero-sdk-rust#567]
### Description

Recently I was testing the Hedera's Rust SDK and I immediately noticed 2 things:

1. Aside from the possible bug it works quite nicely
2. I wasn't able to get token_transfer_with_decimals to work

Further clarification

1. The transaction is created and sent to the frontend to hashpack where it is then confirmed. Upon success message I immediately notice that the HBAR transfer went through with 0 issues but the token transfer sent only 1E-8 of the token amount it was supposed to despite having the decimals set to 8.

All of the claims have been confirmed via HashScan and a bunch of print statements. 

```
TransferTransaction::new()
        .node_account_ids(vec![AccountId::from(3)])
        .transaction_id(TransactionId::generate(payer_id))
        .token_transfer_with_decimals(token_id, owner_id, -token_amount, decimals)
        .token_transfer_with_decimals(token_id, payer_id, token_amount, decimals)
        .hbar_transfer(owner_id, Hbar::new(hbar_amount))
        .hbar_transfer(payer_id, Hbar::new(-hbar_amount))
        .freeze_with(&*CLIENT).unwrap().sign_with_operator(&CLIENT).unwrap()
        .to_bytes()
```

### Steps to reproduce

1. Create a basic TransferTransaction
2. Send to frontend
3. Confirm via HashPack
4. Validate via HashScan

### Hedera network

testnet

### Version

v0.18.0

### Operating system

macOS

**Comment by izik1** [comment]
This is actually not a bug. I'll add some code comments to clarify, as well as explain here:

_All_ transfers of _everything_ are done in the lowest denomination, always. (Even `Hbar`, but that's transparently handled by the SDK)

What setting `decimals` actually does is make it so that you get an error (`hedera::Error::ReceiptStatus { status: Status::UnexpectedTokenDecimals, transaction_id: _ }`) if you wrote it down wrong.

**Comment by DoctorNigel** [comment]
Aw geez I've done it again. Thanks for the help though. I'll make sure I do more testing/research before assigning a possible bug.

Cheers
